name: Run Tests

on: workflow_call

jobs:
  dotnet-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - run: dotnet test
